### ISSUE TITLE
Flux hammer deposits output into input slots with 3 diamond upgrades

### ISSUE THREAD

**Issue by biouxtai** [jeremiahwinsley/ExMachinis#23]
Modpack is All The Mods 7 To The Sky

I have a flux hammer being fed by Integrated Tunnels logic cables connected to 8 diamond tier cobblestone generators.
The flux hammer has all slots filled in less than a second from the input.
[Imgur](https://i.imgur.com/l8EUFzh.png)

On top of the flux hammer is a drawer with plenty of room for the gravel. Flux hammer output was set to top with a hammer.

With two diamond upgrades in the flux hammer, the first slot of 32 gets processed and the output shoved into the drawer. This is correct behavior.
[Imgur](https://i.imgur.com/Pbdbkpi.png)

With three diamond upgrades in the flux hammer, the first slot gets fully processed and the output gravel is placed back in the same slot. Due to the output being a drawer and restricted to gravel the flux hammer stops at this point claiming the output is full. This is incorrect behavior as I expect all output to go to the drawer and not back into the input slot.

First slot correct items.
[Imgur](https://i.imgur.com/xKmb5JQ.png)

First slot now has gravel instead of cobblestone.
[Imgur](https://i.imgur.com/SWALrb2.png)

**Comment by jeremiahwinsley** [comment]
This is the expected behavior - as noted in JEI, it will pull from an inventory above it, if there is a valid recipe. It does so immediately after processing an input, so the pipe would not have the opportunity to fill it first. You can use any other side for outputting to a drawer without pulling.

The "intended" way of doing this is simply place the cobblegen directly on top of the hammer - in ATM 7 Sky the diamond cobblegen produces 4 cobble per tick, which is enough to fully supply a hammer with a netherite upgrade.

**Comment by biouxtai** [comment]
Thank you for the information.  In ATM7 in JEI I do not see any information for the device. I am, perhaps, not looking in the correct spot.
This is what I see when hovering over the item while looking at recipe.

![2023-08-31_13h02_27](https://github.com/jeremiahwinsley/ExMachinis/assets/897029/f8333064-80ad-485f-90f6-b372b86a1868)

**Comment by jeremiahwinsley** [comment]
Are you on pack version 1.2.3? That should have been fixed in Ex Machinis 1.1.1.

**Comment by biouxtai** [comment]
Yes. I'm on 1.2.3.
exmachinis-1.18.2-1.1.0
is the mod version shipped in 1.2.3.  I'll upgrade and see if it fixes it.  Thanks again for the information. I love the mod.
